//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace Terradue.Stars.Data.Model.Metadata.CosmoSkymed.Schemas {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Tag {
        
        private string tagNameField;
        
        private string tagValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TagName {
            get {
                return this.tagNameField;
            }
            set {
                this.tagNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TagValue {
            get {
                return this.tagValueField;
            }
            set {
                this.tagValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", ElementName="DeliveryNote", IsNullable=false)]
    public partial class Metadata {
        public DeliveryNoteProductInfo ProductInfo { get; set; }
        public DeliveryNoteProductDefinitionData ProductDefinitionData { get; set; }
        public DeliveryNoteProcessingInfo ProcessingInfo { get; set; }
        public DeliveryNoteAncillaryDataReference AncillaryDataReference { get; set; }
        public DeliveryNoteAlgorithms Algorithms { get; set; }
        public DeliveryNoteProductCharacteristics ProductCharacteristics { get; set; }
        public DeliveryNotePcdInfo PcdInfo { get; set; }
        public DeliveryNoteFormatInfo FormatInfo { get; set; }
        public DeliveryNoteOtherInfo OtherInfo { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DeliveryNoteAlgorithms {
        
        private Tag[] tagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Tag")]
        public Tag[] Tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DeliveryNoteAncillaryDataReference {
        
        private Tag[] tagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Tag")]
        public Tag[] Tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DeliveryNoteFormatInfo {
        
        private string formatTypeField;
        
        private string prodSpecDocumentField;
        
        private string sampleFormatField;
        
        private string samplesPerPixelField;
        
        private string bitsPerSampleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FormatType {
            get {
                return this.formatTypeField;
            }
            set {
                this.formatTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProdSpecDocument {
            get {
                return this.prodSpecDocumentField;
            }
            set {
                this.prodSpecDocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SampleFormat {
            get {
                return this.sampleFormatField;
            }
            set {
                this.sampleFormatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SamplesPerPixel {
            get {
                return this.samplesPerPixelField;
            }
            set {
                this.samplesPerPixelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BitsPerSample {
            get {
                return this.bitsPerSampleField;
            }
            set {
                this.bitsPerSampleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DeliveryNoteOtherInfo {
        
        private string processingCentreField;
        
        private string providerIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProcessingCentre {
            get {
                return this.processingCentreField;
            }
            set {
                this.processingCentreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProviderId {
            get {
                return this.providerIdField;
            }
            set {
                this.providerIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DeliveryNotePcdInfo {
        
        private DeliveryNotePcdInfoPcdAtt[] pcdAttField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PcdAtt", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DeliveryNotePcdInfoPcdAtt[] PcdAtt {
            get {
                return this.pcdAttField;
            }
            set {
                this.pcdAttField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DeliveryNotePcdInfoPcdAtt {
        
        private DeliveryNotePcdInfoPcdAttName[] nameField;
        
        private DeliveryNotePcdInfoPcdAttValue[] valueField;
        
        private DeliveryNotePcdInfoPcdAttResult[] resultField;
        
        private DeliveryNotePcdInfoPcdAttResultInfo[] resultInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public DeliveryNotePcdInfoPcdAttName[] Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Value", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public DeliveryNotePcdInfoPcdAttValue[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Result", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public DeliveryNotePcdInfoPcdAttResult[] Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ResultInfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public DeliveryNotePcdInfoPcdAttResultInfo[] ResultInfo {
            get {
                return this.resultInfoField;
            }
            set {
                this.resultInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DeliveryNotePcdInfoPcdAttName {
        
        private string datatypeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Datatype {
            get {
                return this.datatypeField;
            }
            set {
                this.datatypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DeliveryNotePcdInfoPcdAttValue {
        
        private string datatypeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Datatype {
            get {
                return this.datatypeField;
            }
            set {
                this.datatypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DeliveryNotePcdInfoPcdAttResult {
        
        private string datatypeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Datatype {
            get {
                return this.datatypeField;
            }
            set {
                this.datatypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DeliveryNotePcdInfoPcdAttResultInfo {
        
        private string datatypeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Datatype {
            get {
                return this.datatypeField;
            }
            set {
                this.datatypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DeliveryNoteProcessingInfo {
        
        private string processingLevelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProcessingLevel {
            get {
                return this.processingLevelField;
            }
            set {
                this.processingLevelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DeliveryNoteProductCharacteristics {
        
        private string azimuthGeometricResolutionField;
        
        private string groundRangeGeometricResolutionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AzimuthGeometricResolution {
            get {
                return this.azimuthGeometricResolutionField;
            }
            set {
                this.azimuthGeometricResolutionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GroundRangeGeometricResolution {
            get {
                return this.groundRangeGeometricResolutionField;
            }
            set {
                this.groundRangeGeometricResolutionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DeliveryNoteProductDefinitionData {
        
        private string productTypeField;
        
        private string sceneSensingStartUTCField;
        
        private string sceneSensingStopUTCField;
        
        private string geoCoordBottomLeftField;
        
        private string geoCoordBottomRightField;
        
        private string geoCoordTopLeftField;
        
        private string geoCoordTopRightField;
        
        private string geoCoordTopRightENField;
        
        private string geoCoordSceneCentreField;
        
        private string satelliteIdField;
        
        private string acquisitionModeField;
        
        private string lookSideField;
        
        private string nearLookAngleField;
        
        private string farLookAngleField;
        
        private string projectionIdField;
        
        private string deliveryModeField;
        
        private string acquisitionStationIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProductType {
            get {
                return this.productTypeField;
            }
            set {
                this.productTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SceneSensingStartUTC {
            get {
                return this.sceneSensingStartUTCField;
            }
            set {
                this.sceneSensingStartUTCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SceneSensingStopUTC {
            get {
                return this.sceneSensingStopUTCField;
            }
            set {
                this.sceneSensingStopUTCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GeoCoordBottomLeft {
            get {
                return this.geoCoordBottomLeftField;
            }
            set {
                this.geoCoordBottomLeftField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GeoCoordBottomRight {
            get {
                return this.geoCoordBottomRightField;
            }
            set {
                this.geoCoordBottomRightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GeoCoordTopLeft {
            get {
                return this.geoCoordTopLeftField;
            }
            set {
                this.geoCoordTopLeftField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GeoCoordTopRight {
            get {
                return this.geoCoordTopRightField;
            }
            set {
                this.geoCoordTopRightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GeoCoordTopRightEN {
            get {
                return this.geoCoordTopRightENField;
            }
            set {
                this.geoCoordTopRightENField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GeoCoordSceneCentre {
            get {
                return this.geoCoordSceneCentreField;
            }
            set {
                this.geoCoordSceneCentreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SatelliteId {
            get {
                return this.satelliteIdField;
            }
            set {
                this.satelliteIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AcquisitionMode {
            get {
                return this.acquisitionModeField;
            }
            set {
                this.acquisitionModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LookSide {
            get {
                return this.lookSideField;
            }
            set {
                this.lookSideField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NearLookAngle {
            get {
                return this.nearLookAngleField;
            }
            set {
                this.nearLookAngleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FarLookAngle {
            get {
                return this.farLookAngleField;
            }
            set {
                this.farLookAngleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProjectionId {
            get {
                return this.projectionIdField;
            }
            set {
                this.projectionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DeliveryMode {
            get {
                return this.deliveryModeField;
            }
            set {
                this.deliveryModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AcquisitionStationId {
            get {
                return this.acquisitionStationIdField;
            }
            set {
                this.acquisitionStationIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DeliveryNoteProductInfo {
        
        private string productNameField;
        
        private string productIdField;
        
        private string missionIdField;
        
        private string uniqueIdentifierField;
        
        private string productGenerationDateField;
        
        private string userRequestIdField;
        
        private string serviceRequestNameField;
        
        private string quickLookPathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProductName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProductId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MissionId {
            get {
                return this.missionIdField;
            }
            set {
                this.missionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UniqueIdentifier {
            get {
                return this.uniqueIdentifierField;
            }
            set {
                this.uniqueIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProductGenerationDate {
            get {
                return this.productGenerationDateField;
            }
            set {
                this.productGenerationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserRequestId {
            get {
                return this.userRequestIdField;
            }
            set {
                this.userRequestIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ServiceRequestName {
            get {
                return this.serviceRequestNameField;
            }
            set {
                this.serviceRequestNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QuickLookPath {
            get {
                return this.quickLookPathField;
            }
            set {
                this.quickLookPathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        Algorithms,
        
        /// <remarks/>
        AncillaryDataReference,
        
        /// <remarks/>
        FormatInfo,
        
        /// <remarks/>
        OtherInfo,
        
        /// <remarks/>
        PcdInfo,
        
        /// <remarks/>
        ProcessingInfo,
        
        /// <remarks/>
        ProductCharacteristics,
        
        /// <remarks/>
        ProductDefinitionData,
        
        /// <remarks/>
        ProductInfo,
        
        /// <remarks/>
        Tag,
    }
}
