name: env_kompsat_5
channels:
  - terradue
  - conda-forge
dependencies:
  - python=3.7
  - pystac
  - ipykernel
  - gdal=3.1.4
  - numpy
  - shapely
  - click
  - pyyaml
  - snuggs
  - matplotlib
  - pip
  - pip:
    - rio_color