// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>psd13</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
using Terradue.OpenSearch.Sentinel.Data.Dimap;


namespace Terradue.Stars.Data.Model.Metadata.Sentinels.Sentinel2
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Level-2A_Tile", Namespace = "https://psd-14.sentinel2.eo.esa.int/PSD/S2_PDI_Level-2A_Tile_Metadata.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("Level-2A_Tile_ID", Namespace = "https://psd-14.sentinel2.eo.esa.int/PSD/S2_PDI_Level-2A_Tile_Metadata.xsd", IsNullable = false)]
    public partial class Level2A_Tile
    {

        private A_GENERAL_INFO_L1C general_InfoField;

        private A_GEOMETRIC_INFO_TILE geometric_InfoField;

        private A_QUALITY_INDICATORS_INFO_TILE quality_Indicators_InfoField;

        /// <summary>
        /// Level2A_Tile class constructor
        /// </summary>
        public Level2A_Tile()
        {
            this.quality_Indicators_InfoField = new A_QUALITY_INDICATORS_INFO_TILE();
            this.geometric_InfoField = new A_GEOMETRIC_INFO_TILE();
            this.general_InfoField = new A_GENERAL_INFO_L1C();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public A_GENERAL_INFO_L1C General_Info
        {
            get
            {
                return this.general_InfoField;
            }
            set
            {
                this.general_InfoField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public A_GEOMETRIC_INFO_TILE Geometric_Info
        {
            get
            {
                return this.geometric_InfoField;
            }
            set
            {
                this.geometric_InfoField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public A_QUALITY_INDICATORS_INFO_TILE Quality_Indicators_Info
        {
            get
            {
                return this.quality_Indicators_InfoField;
            }
            set
            {
                this.quality_Indicators_InfoField = value;
            }
        }
    }


}
