Suppliers:
  Onda:
    Type: Terradue.Data.Stac.Suppliers.DataHubSourceSupplier, Terradue.Data.Stac
    Parameters: [""]
    ServiceUrl: "https://catalogue.onda-dias.eu/dias-catalogue"
    Credentials:
      Username: test
      Password: secret
Translators:
  Onda:
    Type: Terradue.Data.Stac.Translators.AtomToStacTranslator, Terradue.Data.Stac
    Parameters: [""]
Global:
  ForceOverwrite: false
Credentials:
  SciHub:
    Type: HTTP-BASIC
    UriPrefix: https://scihub.copernicus.eu
    Username: test
    Password: secret
