Suppliers:
  Onda:
    Type: Terradue.Data.Suppliers.DataHubSourceSupplier, Terradue.Data.Suppliers
    Parameters: [""]
    ServiceUrl: "https://catalogue.onda-dias.eu/dias-catalogue"
    Credentials:
      Username: test
      Password: secret
Carriers:
  WebDownload:
    NetworkCredentials:
      SciHub:
        UriPrefix: https://scihub.copernicus.eu
        Username: test
        Password: secret
